"""Initial backend database schema

Revision ID: d6cfd26f4343
Revises: None
Create Date: 2026-10-06 20:58:55.076346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6cfd26f4343'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_segments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=100), nullable=False),
    sa.Column('road_name', sa.String(length=255), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('road_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('road_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_road_segments_segment_id'), ['segment_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'GOVERNMENT_OFFICER', 'CONTRACTOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('grievances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=True),
    sa.Column('road_id', sa.String(length=36), nullable=True),
    sa.Column('issue_category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'IN_PROGRESS', 'PENDING_VERIFICATION', 'RESOLVED', 'REJECTED', name='grievancestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['road_id'], ['road_segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grievances_citizen_id'), ['citizen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_road_id'), ['road_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grievances_status'), ['status'], unique=False)

    op.create_table('evidences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidences_grievance_id'), ['grievance_id'], unique=False)

    op.create_table('ml_analysis_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('pipeline_version', sa.String(length=20), nullable=False),
    sa.Column('overall_status', sa.String(length=20), nullable=False),
    sa.Column('total_duration_ms', sa.Float(), nullable=True),
    sa.Column('failure_prediction', sa.JSON(), nullable=True),
    sa.Column('damage_detection', sa.JSON(), nullable=True),
    sa.Column('severity_prediction', sa.JSON(), nullable=True),
    sa.Column('complaint_analysis', sa.JSON(), nullable=True),
    sa.Column('duplicate_detection', sa.JSON(), nullable=True),
    sa.Column('time_to_failure', sa.JSON(), nullable=True),
    sa.Column('maintenance_priority', sa.JSON(), nullable=True),
    sa.Column('stage_summaries', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_analysis_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_analysis_results_grievance_id'), ['grievance_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_analysis_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_analysis_results_grievance_id'))

    op.drop_table('ml_analysis_results')
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidences_grievance_id'))

    op.drop_table('evidences')
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grievances_status'))
        batch_op.drop_index(batch_op.f('ix_grievances_road_id'))
        batch_op.drop_index(batch_op.f('ix_grievances_citizen_id'))

    op.drop_table('grievances')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('road_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_road_segments_segment_id'))

    op.drop_table('road_segments')
    # ### end Alembic commands ###
