"""add contractor workflow and work progress

Revision ID: 600ef8c4509b
Revises: 0a660a35f2f7
Create Date: 2026-10-07 11:16:45.953834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600ef8c4509b'
down_revision: Union[str, None] = '0a660a35f2f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    if 'work_progresses' not in tables:
        op.create_table(
            'work_progresses',
            sa.Column('id', sa.String(length=36), nullable=False),
            sa.Column('work_order_id', sa.String(length=36), nullable=False),
            sa.Column('contractor_id', sa.String(length=36), nullable=False),
            sa.Column('progress_percentage', sa.Integer(), nullable=False),
            sa.Column('note', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
            sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('work_progresses', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_work_progresses_contractor_id'), ['contractor_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_work_progresses_work_order_id'), ['work_order_id'], unique=False)

    evidence_cols = [c['name'] for c in inspector.get_columns('evidences')]
    if 'work_order_id' not in evidence_cols:
        with op.batch_alter_table('evidences', schema=None) as batch_op:
            batch_op.add_column(sa.Column('work_order_id', sa.String(length=36), nullable=True))
            batch_op.create_index(batch_op.f('ix_evidences_work_order_id'), ['work_order_id'], unique=False)
            batch_op.create_foreign_key('fk_evidences_work_order_id_work_orders', 'work_orders', ['work_order_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evidences_work_order_id_work_orders', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_evidences_work_order_id'))
        batch_op.drop_column('work_order_id')

    with op.batch_alter_table('work_progresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_progresses_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_work_progresses_contractor_id'))

    op.drop_table('work_progresses')
    # ### end Alembic commands ###
