"""Add government workflow and work order tables

Revision ID: 0a660a35f2f7
Revises: d6cfd26f4343
Create Date: 2026-10-06 22:19:37.212089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a660a35f2f7'
down_revision: Union[str, None] = 'd6cfd26f4343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('officer_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.Enum('ACCEPT', 'REJECT', name='reviewdecision'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_reviews_grievance_id'), ['grievance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_reviews_officer_id'), ['officer_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('road_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('assigned_contractor_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_VERIFICATION', 'COMPLETED', 'CANCELLED', name='workorderstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_contractor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['road_id'], ['road_segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_assigned_contractor_id'), ['assigned_contractor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_grievance_id'), ['grievance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_road_id'), ['road_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_status'), ['status'], unique=False)

    op.create_table('government_verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('officer_id', sa.String(length=36), nullable=True),
    sa.Column('decision', sa.Enum('APPROVE', 'REJECT', name='verificationdecision'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('government_verifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_verifications_grievance_id'), ['grievance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_verifications_officer_id'), ['officer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_government_verifications_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('workflow_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('grievance_id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=30), nullable=True),
    sa.Column('event_type', sa.Enum('GRIEVANCE_SUBMITTED', 'GRIEVANCE_REVIEWED', 'GRIEVANCE_ACCEPTED', 'GRIEVANCE_REJECTED', 'WORK_ORDER_CREATED', 'WORK_ORDER_ASSIGNED', 'WORK_VERIFICATION_SUBMITTED', 'WORK_VERIFICATION_APPROVED', 'WORK_VERIFICATION_REJECTED', name='workfloweventtype'), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_grievance_id'), ['grievance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_events_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_events_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_grievance_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_events_actor_id'))

    op.drop_table('workflow_events')
    with op.batch_alter_table('government_verifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_verifications_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_government_verifications_officer_id'))
        batch_op.drop_index(batch_op.f('ix_government_verifications_grievance_id'))

    op.drop_table('government_verifications')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_status'))
        batch_op.drop_index(batch_op.f('ix_work_orders_road_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_grievance_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_created_by'))
        batch_op.drop_index(batch_op.f('ix_work_orders_assigned_contractor_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('government_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_reviews_officer_id'))
        batch_op.drop_index(batch_op.f('ix_government_reviews_grievance_id'))

    op.drop_table('government_reviews')
    # ### end Alembic commands ###
